[build]
target = "aarch64-nintendo-switch-freestanding"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[target.aarch64-nintendo-switch-freestanding]
rustflags = [
    "-C", "relocation-model=pic",
]